[connections.connection]
account = "kcb69289"
user = "VAIDEHI"
password = "Kasmodigital"   # or use key-pair / SSO
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "DASH_DB"
schema = "DASH_SCHEMA"
