name: Calculator App CI/CD to Snowflake

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Version Tag
        id: vars
        run: |
          echo "VERSION_TAG=v${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "IMAGE_NAME=calculator-app:$VERSION_TAG" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build --platform=linux/amd64 -t $IMAGE_NAME .

      - name: Docker Login to Snowflake
        run: |
          echo "${{ secrets.SNOWFLAKE_DOCKER_PASSWORD }}" | \
          docker login aqwmurr-ko43468.registry.snowflakecomputing.com -u ${{ secrets.SNOWFLAKE_DOCKER_USERNAME }} --password-stdin

      - name: Tag and Push Docker Image
        run: |
          TAGGED_IMAGE=ubhovfa-kasmo-inc.registry.snowflakecomputing.com/dash_db/dash_schema/image_repo_test/$IMAGE_NAME
          docker tag $IMAGE_NAME $TAGGED_IMAGE
          docker push $TAGGED_IMAGE

